apiVersion: v1
kind: Pod
metadata:
  name: my-pod-anti-aff
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: app
                operator: In
                values:
                -  frontend
  containers:
  - name: arjun-ngin
    image: nginx
